version: 0.0
os: Linux
files: 
  - source: /
    destination: /home//blogprojectdrf
permissions:
  - object: /home/windows/deploymodel
    owner: windows
    group: windows
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 300
        runas: windows
  AfterInstall:
      - location: scripts/instance_os_dependencies.sh
        timeout: 300
        runas: windows
      - location: scripts/python_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/gunicorn.sh
        timeout: 300
        runas: windows
      - location: scripts/nginx.sh
        timeout: 300
        runas: ubuntu
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 300
        runas: windows
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 300
        runas: windows
  
  